server:
  port: 9000

spring:
  datasource:
    url: jdbc:mariadb://124.223.197.249:3306/test?characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    refresh: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples.quickstart: debug